/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElCol: typeof import('element-plus/es')['ElCol']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    MyForm: typeof import('./src/components/my_form/src/MyForm.vue')['default']
    MyFormItem: typeof import('./src/components/my_form/src/MyFormItem.vue')['default']
    MyInput: typeof import('./src/components/my_input/src/MyInput.vue')['default']
    NavBar: typeof import('./src/components/nav_bar/src/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectLocale: typeof import('./src/components/select_locale/src/SelectLocale.vue')['default']
    WangEditor: typeof import('./src/components/wang_editor/src/WangEditor.vue')['default']
  }
}
